version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install awscli --upgrade
      - pip install bandit flake8
  build:
    commands:
      - flake8 backend/app.py  # Check for code styling issues
      - bandit -r backend      # Check for security vulnerabilities
      - docker-compose build   # Build Docker Compose services
      - docker-compose up -d
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - docker-compose.yml
    - frontend/**/*
    - backend/**/*