version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Checking network connectivity..."
      - |
        curl -I https://google.com || { echo "Network issue detected"; exit 1; }
      - echo "Cleaning up yum cache..."
      - yum clean all
      - echo "Updating yum packages..."
      - yum update -y || true
      - echo "Checking Docker installation..."
      - sudo docker --version || (sudo yum install -y docker || sudo apt-get install -y docker.io)
      - echo "Starting Docker daemon..."
      - nohup sudo dockerd > /dev/null 2>&1 &
      - while(! sudo docker info > /dev/null 2>&1); do echo "Waiting for Docker to start..."; sleep 1; done
      - echo "Docker installed and started successfully."
      - echo "Installing Docker Compose..."
      - curl -L "https://github.com/docker/compose/releases/download/2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      - echo "Setting PATH..."
      - export PATH=$PATH:/usr/local/bin
      - echo "Checking Docker Compose version..."
      - /usr/local/bin/docker-compose --version
      - echo "Installing Python packages..."
      - pip install bandit flake8
      - docker info

  pre_build:
    commands:
      - echo "Running Static Code Analysis..."
      - flake8 backend/app.py
      - bandit -r backend

  build:
    commands:
      - echo "Building Docker Compose services..."
      - /usr/local/bin/docker-compose build | tee build.log
      - echo "Tagging Docker images for ECR..."
      - docker tag backend:latest public.ecr.aws/i4a2a9c3/sairaj29test:backend-latest
      - docker tag frontend:latest public.ecr.aws/i4a2a9c3/sairaj29test:frontend-latest
      - echo "Pushing Docker images to ECR..."
      - docker push public.ecr.aws/i4a2a9c3/sairaj29test:backend-latest | tee -a build.log
      - docker push public.ecr.aws/i4a2a9c3/sairaj29test:frontend-latest | tee -a build.log

  post_build:
    commands:
      - echo "Build and push to ECR completed successfully."

artifacts:
  files:
    - docker-compose.yml
    - backend/**/*
    - frontend/**/*
